name: Execute Performance Load Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Client Size"
        required: true
        default: "36k"
        type: choice
        options:
          - 36k
          - 120k
          - 240k
          - 300k
      scriptName:
        description: "Select Test Workflow"
        required: true
        default: "Badging"
        type: choice
        options:
          - Badging
          - CSO
          - WeeklyView
          - MonthlyView
          - SelfSchedule
          - TimeCardReview

jobs:
  load_test:
    name: Run JMeter Load Test for Selected Environment and Script
    runs-on: ['Windows', 'devops-jmeter-large', 'self-hosted', 'symplrdev']

    steps:
      - name: Run on PowerShell Performance Test Script
        shell: pwsh
        run: |
          Tests/Performance/JMeter/Script/Perf_Test_v1.ps1 `
            -ENVIRONMENT "${{ github.event.inputs.environment }}" `
            -SCRIPT_NAME "${{ github.event.inputs.scriptName }}"