name: CICD JMeter Load Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        default: "36k"
        type: choice
        options:
          - 36k
          - 120k
          - 240k
      scriptName:
        description: "Select JMeter Script Name"
        required: true
        default: "1_Badging"
        type: choice
        options:
          - '1_Badging'
          - '2_SelfSchedule'
          - '3_Scheduler'
          - '4_MySchedule'
          - '5_TCS'
          - '6_CSO'
      lgCombination:
        description: "Select Number of Load Generators (4, 8, 12, 18)"
        required: true
        default: "4"
        type: choice
        options:
          - '4'
          - '8'
          - '12'
          - '18'

jobs:
  load_test:
    name: Run JMeter Load Test for Selected Environment and Script
    runs-on: [self-hosted, d87wfmjmrig2c01.1]

    env:
      # Base paths for each environment
      36k: "C:\\PerformanceTesting\\Scripts\\MockIDP_Optimus2_Testing3\\"
      120k: "C:\\PerformanceTesting\\Scripts\\120k_Script\\"
      240k: "C:\\PerformanceTesting\\Scripts\\MockIDP_Optimus2_Testing1_240K\\"

      # Load Generator (LG) IP combinations
      LOAD_GENERATORS_4: "10.253.69.97,10.253.69.98,10.253.69.99,10.253.69.100"
      LOAD_GENERATORS_8: "10.253.69.97,10.253.69.98,10.253.69.99,10.253.69.100,10.253.69.101,10.253.69.102,10.253.69.103,10.253.69.105"
      LOAD_GENERATORS_12: "10.253.69.97,10.253.69.98,10.253.69.99,10.253.69.100,10.253.69.101,10.253.69.102,10.253.69.103,10.253.69.105,10.253.68.97,10.253.68.98,10.253.68.99,10.253.68.100"
      LOAD_GENERATORS_18: "10.253.69.97,10.253.69.98,10.253.69.99,10.253.69.100,10.253.69.101,10.253.69.102,10.253.69.103,10.253.69.104,10.253.69.105,10.253.68.97,10.253.68.98,10.253.68.99,10.253.68.100,10.253.68.27,10.253.68.28,10.253.68.29,10.253.68.30,10.253.69.11"

    steps:
      - name: Run JMeter Load Test
        shell: cmd
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          SCRIPT_NAME: ${{ github.event.inputs.scriptName }}
          LG_COMBINATION: ${{ github.event.inputs.lgCombination }}
        run: |
          REM Define JMeter binary and properties paths
          SET jmeterBin=C:\PerformanceTesting\Tool\apache-jmeter-5.4\apache-jmeter-5.4\apache-jmeter-5.4\bin

          REM Determine the base path based on the environment input
          IF "%ENVIRONMENT%"=="36k" SET basePath=%36k%
          IF "%ENVIRONMENT%"=="120k" SET basePath=%120k%
          IF "%ENVIRONMENT%"=="240k" SET basePath=%240k%

         
          REM Construct the script path based on the selected script name
          SET jmeterScript=%basePath%\%SCRIPT_NAME%.jmx

          REM Select the Load Generators combination based on the input
          IF "%LG_COMBINATION%"=="4" SET loadGenerators=%LOAD_GENERATORS_4%
          IF "%LG_COMBINATION%"=="8" SET loadGenerators=%LOAD_GENERATORS_8%
          IF "%LG_COMBINATION%"=="12" SET loadGenerators=%LOAD_GENERATORS_12%
          IF "%LG_COMBINATION%"=="18" SET loadGenerators=%LOAD_GENERATORS_18%

          REM Ensure the JMeter script exists
          IF NOT EXIST "%jmeterScript%" (
            ECHO JMeter script not found at %jmeterScript%
            EXIT /B 1
          )

          REM Change to the JMeter binary directory
          CD /D %jmeterBin%

          REM Run JMeter in non-GUI mode for distributed testing
          jmeter -n -t "%jmeterScript%" -R "%loadGenerators%"
